### ISSUE TITLE
Allow fetching Holt-Winters parameters at runtime

### ISSUE THREAD

**Issue by jthomperoo** [jthomperoo/predictive-horizontal-pod-autoscaler#27]
The alpha, beta, and gamma values for Holt-Winters are currently predetermined and set at configuration time. A useful feature would be to allow these parameters to be fetched/calculated at runtime - for example with a grid search.

_Originally posted by @shubhamitc in https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler/issues/26#issuecomment-640549238_

Proposed solution is providing some kind of hook functionality that would allow configuration of an HTTP endpoint or a Python script to run to determine these values at runtime.

**Comment by shubhamitc** [comment]
@jthomperoo i would like to work on it. Can we discuss the way forward?

**Comment by jthomperoo** [comment]
Hi, that's great to hear! I'll outline some steps here just to get you started on the codebase from the README.

> ## Developing this project
> ### Environment
> Developing this project requires these dependencies:
> 
> * [Go](https://golang.org/doc/install) >= `1.13`
> * [Golint](https://github.com/golang/lint)
> * [Docker](https://docs.docker.com/install/)
> 
> To view docs locally, requires:
> 
> * [mkdocs](https://www.mkdocs.org/)
> 
> ### Commands
> 
> * `make` - builds the Predictive HPA binary.
> * `make docker` - builds the Predictive HPA image.
> * `make lint` - lints the code.
> * `make unittest` - runs the unit tests
> * `make vendor` - generates a vendor folder.
> * `make doc` - hosts the documentation locally, at `127.0.0.1:8000`.

So make sure you have `Golang >=1.13`, Docker and Golint installed on your development machine.
You will also need a Kubernetes cluster to be able to test your changes out on, either from a cloud provider (for example I like to use [DigitalOcean](https://www.digitalocean.com/products/kubernetes/)) or running the cluster locally with [MiniKube](https://kubernetes.io/docs/tasks/tools/install-minikube/) or [k3d](https://www.digitalocean.com/products/kubernetes/).

To test out your changes, install the [Custom Pod Autoscaler Operator](https://github.com/jthomperoo/custom-pod-autoscaler-operator) on your cluster, see the [install guide here](https://github.com/jthomperoo/custom-pod-autoscaler-operator/blob/master/INSTALL.md).

Any changes made should be documented (see the `docs/` folder), unit tested and pass the linter `make lint`.

Now onto the changes themselves.

So the proposed solution is some kind of hook functionality, which would be configurable by users. The config would look something like this:
```yaml
models:
- type: HoltWinters
  name: HoltWintersPrediction
  perInterval: 1
  holtWinters:
    alphaFetch:
      method: "GET"
      url: "https://<url>/<endpoint_that_returns_alpha_value>"
      successCodes:
        - 200
      parameterMode: query
    betaFetch:
      method: "GET"
      url: "https://<url>/<endpoint_that_returns_beta_value>"
      successCodes:
        - 200
      parameterMode: query
    gammaFetch:
      method: "GET"
      url: "https://<url>/<endpoint_that_returns_gamma_value>"
      successCodes:
        - 200
      parameterMode: query
    seasonLength: 6
    storedSeasons: 4
    method: "additive"
decisionType: "maximum"
metrics:
- type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 50
```

The key bit here is the new `alphaFetch`, `betaFetch` and `gammaFetch` - these should be set up using some of the 'method' system from the Custom Pod Autoscaler Framework, this would save you having to rewrite lots of code:

https://github.com/jthomperoo/custom-pod-autoscaler/tree/master/execute
https://custom-pod-autoscaler.readthedocs.io/en/latest/user-guide/methods/

You could specify that they have to conform to a certain format, e.g. in JSON:

```json
{
    "value": 0.2
}
```

Or you could just allow them to return the raw value, it is up to you, I'm not sure which of these approaches is best.

Also in the configuration if these hooks are provided the normal hardcoded `alpha`, `beta` and `gamma` values should be ignored, if they are not provided the hardcoded values should be used.

The holt-winters code should then be updated to execute these hooks if they are provided to fetch these tuning values:

https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler/blob/master/prediction/holtwinters/holtwinters.go

I think that covers most of it, I'm sure there are some other complexities that I've missed, if you have any questions feel free to ask me!

Thanks for taking the time to help out!

**Comment by shubhamitc** [comment]
IMHO, you can serve all three alpha, beta, and gamma via a single API response. So if the parameterMode is a query, we can just ask for 1 endpoint and paramerterMode once. See if this makes sense

```
models:
- type: HoltWinters
  name: HoltWintersPrediction
  perInterval: 1
  holtWinters:
    paramFetchEndpoint: "https://<url>/<endpoint_that_returns_alpha_value>"
    paramStatusCode: 200
    parameterMode: query
    paramFetchMethod: "GET"
    alphaFetch:
      parameterMode: query
    seasonLength: 6
    storedSeasons: 4
    method: "additive"
decisionType: "maximum"
metrics:
- type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 50
```

This should make the configuration pretty small and will give you the option to either use the old hardcoded values for param as well as fetchAPI. Let me know your thoughts.
